name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Z3 (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libz3-dev

      - name: Install Z3 (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install z3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run Tests
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            export CGO_CFLAGS="-I$(brew --prefix z3)/include"
            export CGO_LDFLAGS="-L$(brew --prefix z3)/lib"
          fi
          go test -v ./...
